package com.xiangbinwang.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class OrderOuter implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.trd_side
     *
     * @mbggenerated
     */
    private Integer trdSide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.order_type
     *
     * @mbggenerated
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.order_ID
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.order_IDEx
     *
     * @mbggenerated
     */
    private String orderIdex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.qty
     *
     * @mbggenerated
     */
    private Double qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.fill_qty
     *
     * @mbggenerated
     */
    private Double fillQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.fill_avg_price
     *
     * @mbggenerated
     */
    private Double fillAvgPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.last_err_msg
     *
     * @mbggenerated
     */
    private String lastErrMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_outer.sec_market
     *
     * @mbggenerated
     */
    private Integer secMarket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_outer
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.id
     *
     * @return the value of order_outer.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.id
     *
     * @param id the value for order_outer.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.trd_side
     *
     * @return the value of order_outer.trd_side
     *
     * @mbggenerated
     */
    public Integer getTrdSide() {
        return trdSide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.trd_side
     *
     * @param trdSide the value for order_outer.trd_side
     *
     * @mbggenerated
     */
    public void setTrdSide(Integer trdSide) {
        this.trdSide = trdSide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.order_type
     *
     * @return the value of order_outer.order_type
     *
     * @mbggenerated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.order_type
     *
     * @param orderType the value for order_outer.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.order_status
     *
     * @return the value of order_outer.order_status
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.order_status
     *
     * @param orderStatus the value for order_outer.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.order_ID
     *
     * @return the value of order_outer.order_ID
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.order_ID
     *
     * @param orderId the value for order_outer.order_ID
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.order_IDEx
     *
     * @return the value of order_outer.order_IDEx
     *
     * @mbggenerated
     */
    public String getOrderIdex() {
        return orderIdex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.order_IDEx
     *
     * @param orderIdex the value for order_outer.order_IDEx
     *
     * @mbggenerated
     */
    public void setOrderIdex(String orderIdex) {
        this.orderIdex = orderIdex == null ? null : orderIdex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.code
     *
     * @return the value of order_outer.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.code
     *
     * @param code the value for order_outer.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.name
     *
     * @return the value of order_outer.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.name
     *
     * @param name the value for order_outer.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.qty
     *
     * @return the value of order_outer.qty
     *
     * @mbggenerated
     */
    public Double getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.qty
     *
     * @param qty the value for order_outer.qty
     *
     * @mbggenerated
     */
    public void setQty(Double qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.price
     *
     * @return the value of order_outer.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.price
     *
     * @param price the value for order_outer.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.create_date
     *
     * @return the value of order_outer.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.create_date
     *
     * @param createDate the value for order_outer.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.update_date
     *
     * @return the value of order_outer.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.update_date
     *
     * @param updateDate the value for order_outer.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.fill_qty
     *
     * @return the value of order_outer.fill_qty
     *
     * @mbggenerated
     */
    public Double getFillQty() {
        return fillQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.fill_qty
     *
     * @param fillQty the value for order_outer.fill_qty
     *
     * @mbggenerated
     */
    public void setFillQty(Double fillQty) {
        this.fillQty = fillQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.fill_avg_price
     *
     * @return the value of order_outer.fill_avg_price
     *
     * @mbggenerated
     */
    public Double getFillAvgPrice() {
        return fillAvgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.fill_avg_price
     *
     * @param fillAvgPrice the value for order_outer.fill_avg_price
     *
     * @mbggenerated
     */
    public void setFillAvgPrice(Double fillAvgPrice) {
        this.fillAvgPrice = fillAvgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.last_err_msg
     *
     * @return the value of order_outer.last_err_msg
     *
     * @mbggenerated
     */
    public String getLastErrMsg() {
        return lastErrMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.last_err_msg
     *
     * @param lastErrMsg the value for order_outer.last_err_msg
     *
     * @mbggenerated
     */
    public void setLastErrMsg(String lastErrMsg) {
        this.lastErrMsg = lastErrMsg == null ? null : lastErrMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_outer.sec_market
     *
     * @return the value of order_outer.sec_market
     *
     * @mbggenerated
     */
    public Integer getSecMarket() {
        return secMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_outer.sec_market
     *
     * @param secMarket the value for order_outer.sec_market
     *
     * @mbggenerated
     */
    public void setSecMarket(Integer secMarket) {
        this.secMarket = secMarket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_outer
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", trdSide=").append(trdSide);
        sb.append(", orderType=").append(orderType);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderIdex=").append(orderIdex);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", qty=").append(qty);
        sb.append(", price=").append(price);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", fillQty=").append(fillQty);
        sb.append(", fillAvgPrice=").append(fillAvgPrice);
        sb.append(", lastErrMsg=").append(lastErrMsg);
        sb.append(", secMarket=").append(secMarket);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}