package com.xiangbinwang.dao.mappers.mappers;

import com.xiangbinwang.dao.entity.OrderOuter;
import java.util.List;

public interface OrderOuterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_outer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_outer
     *
     * @mbggenerated
     */
    int insert(OrderOuter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_outer
     *
     * @mbggenerated
     */
    OrderOuter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_outer
     *
     * @mbggenerated
     */
    List<OrderOuter> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_outer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderOuter record);
}