package com.xiangbinwang.dao.mappers;

import com.xiangbinwang.dao.entity.UserKey;
import com.xiangbinwang.interceptor.BrokerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbggenerated
     */
    int insert(UserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbggenerated
     */
    UserKey selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbggenerated
     */
    List<UserKey> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_key
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserKey record);

    BrokerKey getUser(@Param("apiKey") String accessKey);
}